language: java
script: 
 - chmod +x gradlew
 
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
 
branches:
   only:
    - master

services:
  - mongodb