#spring
#  data
#    mongodb
#      database: dictionary
#      port: 27017
#      host: localhost
      
spring:
 # h2:
  #  console:
   #   enabled: true
    #  path: /h2-console
  datasource:
      url: jdbc:postgresql://localhost:5432/postgre_dic
      #driverClassName: com.mysql.cj.jdbc.Driver
      username: postgres
      password: 
    
  jpa:
    properties:
       hibernate:
        dialect:  org.hibernate.dialect.PostgreSQL9Dialect
        temp:
          use_jdbc_metadata_defaults : false
       jdbc:
          lob.non_contextual_creation: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
     

server:
  port: 8899