#spring
#  data
#    mongodb
#      database: dictionary
#      port: 27017
#      host: localhost
      
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
      url: jdbc:mysql://localhost:3306/dictionary?useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: aaaa
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      #naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create

server:
  port: 8899